spring.application.name: sbsn
security.jwt.token.secret-key: 7Z8X9y7k2F3s4D6g8H9j0K1l2M3n4B5v6C7b8N9m0P1o2I3u4Y5t6G7b8V9n0M=

spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/socialnetworkdb
    username: socialnetwork
    password: socialnetwork
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate